### PR TITLE
Use fontFeatures to extract OpenType features

### LINKED ISSUE #49: extractor does not generate features.fea for OpenType features
All UFO files generated by extractor does not produce the [Adobe [OpenType Feature File `features.fea`](http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html) according to [UFO 3 specification](https://unifiedfontobject.org/versions/ufo3/). This will make the font lose all OpenType features when converting into UFO. (UFO export of FontForge did include `features.fea`.

Since this is using `fontTools` for binary OpenType font file, the [`feaLib`](https://fonttools.readthedocs.io/en/latest/feaLib/index.html#generation-interrogation) can be used to accomplish the task.

### PR DESCRIPTION
**Pull request by NightFurySL2001**
Fix #49

### CODE REVIEW

**Comment by benkiel** [comment]
LGTM

**Comment by typemytype** [comment]
can this option be optional? 

it super silly to embed 106mb of pure numpy just to extract features... 

image

@simoncozens I guess it must be possible to reduce dependencies for [fontFeatures](https://github.com/simoncozens/fontfeatures)

**Comment by simoncozens** [comment]
Probably, yes. It looks like the numpy dependency is coming in through beziers.py. I should rip out all the beziers/path related stuff from fontFeatures so that it only deals with feature code.

**Comment by typemytype** [comment]
that would be super! 

the first import of `numpy` via `fontFeatures` is in `glyphTools.ckmeans`

**Comment by benkiel** [comment]
@typemytype I'm going to make `fontFeatures` an optional install, fyi. Just haven't gotten to it yet. Next week.

**Comment by simoncozens** [comment]
fontFeatures 1.8.0 now has greatly reduced dependencies.

**Comment by NightFurySL2001** [comment]
@simoncozens verified, pyinstaller build went down from ~42MB to ~12MB.

**Pull request merged**
