### PR TITLE
Extract TrueType instructions to TTX assembly format

### PR DESCRIPTION
**Pull request by jenskutilek**
Just keeping track of my experiments here ... related discussion: https://github.com/unified-font-object/ufo-spec/issues/93

### CODE REVIEW

**Comment by jenskutilek** [comment]
I have changed the code so the extracted TrueType programs are in FontTools TTX assembly format.

The PR depends on an unmerged PR in FontTools, that's why the checks fail.

**Comment by jenskutilek** [comment]
The checks fail because of Py3-only syntax. Is Python 2.7 support still a concern for extractor?

**Comment by typemytype** [comment]
Nope, py 2.7 can be removed. Maybe in a different PR which you can pull into this PR

**Comment by jenskutilek** [comment]
I think this is ready to be merged. Should we wait until the UFO spec (https://github.com/unified-font-object/ufo-spec/pull/94) has been officially updated?

**Comment by benkiel** [comment]
@jenskutilek Spec has been updated, merging.

**Comment by jenskutilek** [comment]
Thank you!

**Comment by moyogo** [comment]
@jenskutilek @benkiel 
The component flags (round, useMyMetrics, overlap) are not part of the UFO `public.truetype.instructions` spec.
See https://github.com/unified-font-object/ufo-spec/issues/162

**Comment by jenskutilek** [comment]
I've disabled extraction of composite flags for now: #32

**Comment by moyogo** [comment]
Thanks @jenskutilek. Sorry for the trouble.

**Pull request merged**
