### PR TITLE
Handle rounding of component transforms when calculating glyph hashes

### LINKED ISSUE #65: Glyph hash sometimes calculated incorrectly
I have an OpenType font which I'm trying to convert to UFO and build back.

Conversion works fine, but both `fontmake` as well as the modified `roundtrip.py` file from your test directory build a much smaller TTF file as a result, because some hinting instructions are lost in the process due to glyph hash mismatches.

I've modified my copy of ufo2ft to output both hashes in such case, and from the few which aren't SHA-512 hashed, it appears that in some cases, the order of either contours or points gets reversed in different circumstances. Also, it seems like in some other cases there's an issue with floats vs ints ending up in the hash string.

I'm wondering which library i should blame for this. Here's an example file: [Jon.zip](https://github.com/user-attachments/files/16751176/Jon.zip).

### PR DESCRIPTION
**Pull request by jenskutilek**
Update calculation of composite glyph hashes to match ufo2ft. Fixes #65.

### CODE REVIEW

**Comment by jenskutilek** [comment]
It's possible. I'll look for a suitable test case. The TTFs included in the tests have no instructions on composites (most TTFs in the wild don't have them).

**Comment by jenskutilek** [comment]
Yes, the instructions of the referenced glyphs will be applied, and after that, any instructions that are in the composite glyph*. For example, if you want to improve the centering of an accent over a base glyph.

* If I understand it correctly, to be more precise, each component will be grid-fitted on its own in its original untransformed state, then those grid-fitted outlines are composed into the composite glyph, possibly with offsets, scaling, and rounding to the grid via a flag, and then the instructions of the composite glyph are evaluated to grid-fit the combined outlines again.

**Comment by rimas-kudelis** [comment]
Is there something you're still wanting to do in this pull request?

**Comment by benkiel** [comment]
@jenskutilek thanks! Merged

**Pull request merged**
